### ISSUE TITLE
Please replace print with a supressable warning in fdata

### ISSUE THREAD

**Issue by ghost** [moviedo5/fda.usc#1]
fdata contains, in part:

`if ((np!=lentt) && (nc==lentt)) {
         out[["data"]]=matrix(out[["data"]],ncol=nc)
         nc<-1
         print("Warning: The transposed data is returned")      }
else    out[["data"]]=out[["data"]]`

That means that the warning in that case cannot be suppressed, even with _suppressWarnings_(.). Please replace with a _bond fide_ warning.

Thanks.

**Comment by moviedo5** [comment]
fdata function is now updated

Thanks for warning!,

Manuel
