### ISSUE TITLE
Error in kmeans.fd while running example

### ISSUE THREAD

**Issue by GFabien** [moviedo5/fda.usc#10]
Hello there, I was trying the function `kmeans.fd` and ran the first example. Unfortunately, this example failed. It raises an error because of line 153. Probably, the condition `(i<max.iter) && (!same_centers)` should be replaced with something like `(i<max.iter) && (!any(same_centers))`.

**Comment by FelipeWaks** [comment]
Hello, i've bumped with the same problem. I've changed the condition to while ((i < max.iter) && (!all(same_centers))). 
This means that loop will break if i >= max iter or if ALL the centers stay the same.

**Comment by GFabien** [comment]
Hello, yes indeed! It seems that the code has been updated since my comment last year on the master branch. The `same_centers` variable can no longer be a vector. Therefore I'm closing this comment, feel free to reopen if it still produces an error for you
